/* tslint:disable */
/* eslint-disable */
/**
 * swapi.dev
 * Adapted schema for swapi.dev
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export * from "./api/films-api";
export * from "./api/people-api";
export * from "./api/planets-api";
export * from "./api/species-api";
export * from "./api/starships-api";
export * from "./api/vehicles-api";
